#!/bin/bash

# Проверка на наличие прав суперпользователя
if [[ $EUID -ne 0 ]]; then
    echo "Этот скрипт должен выполняться от имени суперпользователя (root)." 1>&2
    exit 1
fi

# Создание резервной копии текущего файла конфигурации SSH
echo "Создаю резервную копию текущего файла конфигурации SSH..."
sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

# Настраиваю SSH конфигурацию
echo "Настраиваю SSH конфигурацию..."
{
    echo "# Include /etc/ssh/sshd_config.d/*.conf"
    echo "# Port 22"
    echo "# PermitRootLogin yes"
    echo "# PubkeyAuthentication yes"
    echo "# AuthorizedKeysFile .ssh/authorized_keys"
    echo "# PasswordAuthentication yes"
    echo "# KbdInteractiveAuthentication yes"
    echo "# UsePAM yes"
    echo "# X11Forwarding yes"
    echo "# PrintMotd yes"
    echo "# AcceptEnv LANG LC_*"
    echo "# Subsystem sftp /usr/lib/openssh/sftp-server"
    echo ""
    echo "Include /etc/ssh/sshd_config.d/*.conf"
    echo "Port 8222"
    echo "PermitRootLogin no"
    echo "PubkeyAuthentication yes"
    echo "AuthorizedKeysFile /home/random/.ssh/authorized_keys"
    echo "PasswordAuthentication no"
    echo "KbdInteractiveAuthentication no"
    echo "UsePAM yes"
    echo "X11Forwarding yes"
    echo "PrintMotd no"
    echo "AcceptEnv LANG LC_*"
    echo "Subsystem sftp /usr/lib/openssh/sftp-server"
} | sudo tee /etc/ssh/sshd_config > /dev/null

# Открытие нового порта 8222 через UFW
echo "Открываю порт 8222 для SSH..."
sudo ufw allow 8222/tcp

# Создание пользователя random с рут правами
echo "Создаю пользователя random..."
username="random"
password="VwZ-R8M-Gy4-fgL"  # Установленный пароль
sudo useradd -m -s /bin/bash -G sudo "$username"
echo "$username:$password" | sudo chpasswd

# Запрет входа под пользователем root
echo "Запрещаю вход под пользователем root..."
sudo passwd -l root

# Создание пары ключей
echo "Создаю пару SSH-ключей..."
key_path="/home/$username/.ssh/id_rsa"
sudo mkdir -p /home/$username/.ssh
sudo ssh-keygen -t rsa -b 2048 -f "$key_path" -N ""

# Установка прав на ключи
sudo chmod 700 /home/$username/.ssh
sudo chmod 600 "$key_path"
sudo chown "$username:$username" "$key_path"
sudo chown "$username:$username" "$key_path.pub"

# Добавление публичного ключа в файл authorized_keys
echo "Добавляю публичный ключ в файл authorized_keys..."
sudo cat "$key_path.pub" | sudo tee /home/$username/.ssh/authorized_keys > /dev/null
sudo chmod 600 /home/$username/.ssh/authorized_keys
sudo chown "$username:$username" /home/$username/.ssh/authorized_keys

# Вывод приватного ключа
echo "Пожалуйста, скопируйте и сохраните следующий приватный ключ:"
echo ""
sudo cat "$key_path"
echo ""
echo "Не забудьте добавить публичный ключ ($key_path.pub) на ваш сервер."

# Перезапуск SSH
sudo systemctl restart ssh

echo "Настройка завершена. Вы можете входить в систему под пользователем $username с использованием ключа."
